name: Teste

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World!"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo "Hello Brazil"

  job3:
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - run: echo "Hello China"

  job4:
    runs-on: ubuntu-latest
    needs: job3
    steps:
      - run: echo "Hello Canada!"

  build:
    runs-on: ubuntu-latest
    needs: job4  # Espera job4 terminar antes de iniciar

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar dependências
        run: dotnet restore

      - name: Compilar projeto
        run: dotnet build --configuration Release
